theme: jekyll-theme-merlot

# Site settings
title: Saloni Bansal
name: Saloni Bansal


skills:
- Golang


roles:
 - title: Data Scientist
   start: September 2019
   end: Ongoing
   employer: nference.ai
   description: nference's mission is to synthesize the exponentially growing biomedical knowledge. <br>
   It uses state-of-the-art neural networks (shallow and deep learning models) for real-time, automated extraction of knowledge from the commercial, scientific and regulatory body of literature.
  

education:
 - level: Masters of Technology (M. Tech.)
   date: July, 2019
   subject: Computer Science
   school: Indian Institute of Science, Bengaluru
  
